In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [104]:
amazon=pd.read_csv("/content/amazon_sales_with_stock.csv")

In [105]:
amazon.shape

(128975, 28)

In [106]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  object
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  object
 16  ship-state          128942 non-null  object
 17  ship-postal-code    128942 non-null  float64
 18  ship-country        128942 non-null  object
 19  promotion-ids       79822 non-null   object
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   object
 22  SKU Code            121269 non-null  object
 23  Design No.          121269 non-null  object
 24  Stock               121269 non-null  float64
 25  Stock Category      121269 non-null  object
 26  Stock Size          121269 non-null  object
 27  Color               121269 non-null  object
dtypes: bool(1), float64(3), int64(1), object(23)
memory usage: 26.7+ MB

# There are null value in column[Courier Status,currency,Courier Status,Amount,ship city ,ship state,postalcode, country,fullfield by,  skucode,stock, stock category,stocksize,colour

In [107]:
amazon.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'SKU Code', 'Design No.', 'Stock',
       'Stock Category', 'Stock Size', 'Color'],
      dtype='object')

In [108]:
amazon.describe()

                 Qty         Amount  ship-postal-code          Stock
count  128975.000000  121180.000000     128942.000000  121269.000000
mean        0.904431     648.561465     463966.236509      68.516496
std         0.313354     281.211687     191476.764941     143.740394
min         0.000000       0.000000     110001.000000       0.000000
25%         1.000000     449.000000     382421.000000       5.000000
50%         1.000000     605.000000     500033.000000      14.000000
75%         1.000000     788.000000     600024.000000      67.000000
max        15.000000    5584.000000     989898.000000    1234.000000

In [109]:
amazon[['Sales Channel',"Fulfilment"]].head(11)

   Sales Channel Fulfilment
0      Amazon.in   Merchant
1      Amazon.in   Merchant
2      Amazon.in     Amazon
3      Amazon.in   Merchant
4      Amazon.in     Amazon
5      Amazon.in     Amazon
6      Amazon.in     Amazon
7      Amazon.in   Merchant
8      Amazon.in     Amazon
9      Amazon.in     Amazon
10     Amazon.in     Amazon

In [110]:
amazon.sample(10)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,ship-country,promotion-ids,B2B,fulfilled-by,SKU Code,Design No.,Stock,Stock Category,Stock Size,Color
61625,407-7210185-7543537,05-22-22,Shipped,Amazon,Amazon.in,Expedited,MEN5031,MEN5031-KR-XL,kurta,XL,...,IN,NaN,False,NaN,MEN5031-KR-XL,MEN5031,21.0,KURTA,XL,Maroon
1381,405-9070448-4342702,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0338,J0338-DR-XL,Western Dress,XL,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,J0338-DR-XL,J0338,116.0,DRESS,XL,Mustard
26162,402-9235175-5092318,04-15-22,Shipped,Amazon,Amazon.in,Expedited,NW015,NW015-TP-PJ-XXL,Set,XXL,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NW015-TP-PJ-XXL,NW015,6.0,NIGHT WEAR,XXL,Grey
114789,402-5420367-2549964,06-10-2022,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,MEN5022,MEN5022-KR-L,kurta,L,...,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,MEN5022-KR-L,MEN5022,4.0,KURTA,L,Green
47515,404-8612809-6062757,04-01-2022,Shipped,Amazon,Amazon.in,Expedited,JNE3463,JNE3463-KR-M,kurta,M,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,JNE3463-KR-M,JNE3463,153.0,KURTA,M,Light Green
115171,403-0452453-5883504,06-10-2022,Shipped,Amazon,Amazon.in,Expedited,JNE3463,JNE3463-KR-XL,kurta,XL,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,JNE3463-KR-XL,JNE3463,145.0,KURTA,XL,Light Green
6332,405-9676880-0277122,04-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3619,JNE3619-KR-XL,kurta,XL,...,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,JNE3619-KR-XL,JNE3619,10.0,KURTA,XL,Black
55756,408-0105046-8101124,05-26-22,Cancelled,Merchant,Amazon.in,Standard,J0401,J0401-DR-S,Western Dress,S,...,IN,NaN,False,Easy Ship,J0401-DR-S,J0401,6.0,DRESS,S,Yellow
57995,171-0117148-9870712,05-25-22,Cancelled,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-XS,Western Dress,XS,...,IN,NaN,False,Easy Ship,JNE3798-KR-XS,JNE3798,13.0,KURTA,XS,Teal
103017,407-6122094-5827567,06-19-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-A-XL,Western Dress,XL,...,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
amazon.columns = amazon.columns.str.replace(' ', '_').str.replace('-', '_').str.title().str.strip()
amazon.columns

Index(['Order_Id', 'Date', 'Status', 'Fulfilment', 'Sales_Channel',
       'Ship_Service_Level', 'Style', 'Sku', 'Category', 'Size', 'Asin',
       'Courier_Status', 'Qty', 'Currency', 'Amount', 'Ship_City',
       'Ship_State', 'Ship_Postal_Code', 'Ship_Country', 'Promotion_Ids',
       'B2B', 'Fulfilled_By', 'Sku_Code', 'Design_No.', 'Stock',
       'Stock_Category', 'Stock_Size', 'Color'],
      dtype='object')

In [112]:
amazon.rename(columns={"Ship_City":"City",'Ship_State':"State","Ship_Postal_Code":"Postal_Code","Stock_Category":"Category",'Stock_Size':"Size"},inplace=True)

In [113]:
amazon["Date"]=pd.to_datetime(amazon["Date"])
amazon["Day"]=amazon["Date"].dt.day_name()

/tmp/ipykernel_2515/3733272162.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon["Date"]=pd.to_datetime(amazon["Date"])

Duplicte row [sku, sku_code]  we drop skucode

In [114]:
amazon[['Sku','Sku_Code']]
amazon.drop('Sku_Code',axis=1,inplace=True)

In [115]:
amazon.columns

Index(['Order_Id', 'Date', 'Status', 'Fulfilment', 'Sales_Channel',
       'Ship_Service_Level', 'Style', 'Sku', 'Category', 'Size', 'Asin',
       'Courier_Status', 'Qty', 'Currency', 'Amount', 'City', 'State',
       'Postal_Code', 'Ship_Country', 'Promotion_Ids', 'B2B', 'Fulfilled_By',
       'Design_No.', 'Stock', 'Category', 'Size', 'Color', 'Day'],
      dtype='object')

In [116]:
print(amazon["City"].value_counts())
print(amazon.groupby('City')['Amount'].sum())

City
BENGALURU              11217
HYDERABAD               8074
MUMBAI                  6126
NEW DELHI               5795
CHENNAI                 5421
                       ...
shimoga                    1
Bangluru                   1
Dombiwali                  1
Begumpet, Hyderabad        1
Badlapur , Thane           1
Name: count, Length: 8955, dtype: int64
City
(Chikmagalur disterict).     (N.R pur thaluku)     389.0
(Via Cuncolim)Quepem,South Goa                    1163.0
,HYDERABAD                                         563.0
,raibarely road faizabad (Ayodhya)                1122.0
..katra                                            641.0
                                                   ...
yavatmal                                           735.0
yazali                                             487.0
yellapur                                           824.0
zirakpur                                           852.0
लखनऊ                                              2003.0
Name: Amount, Length: 8955, dtype: float64

In [117]:
import re
import pandas as pd

def clean(city):
    if pd.isna(city):
        return 'Unknown'

    city = str(city).lower().strip()
    city = re.sub(r'[^a-z\s]', ' ', city)
    city = re.sub(r'\s+', ' ', city).strip()

    if len(city) < 2:
        return 'Unknown'

    return city.title()

In [118]:
amazon["City"]=amazon["City"].apply(clean)

In [119]:
"""import re
def clean(city):
  if pd.isna(city):
      return 'unknown'
  city = str(city).lower().strip()
  city=re.sub(r'[^a-z\s]',' ',city)
  city=re.sub(r'\s+'," ",city).strip()
  city=city.title()
  if len(city)<2 :
    return 'unknown'
amazon['City']=amazon['City'].apply(clean)  """

<>:6: SyntaxWarning: invalid escape sequence '\s'
<>:6: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_2515/3624553271.py:6: SyntaxWarning: invalid escape sequence '\s'
  city=re.sub(r'[^a-z\s]',' ',city)

'import re\ndef clean(city):\n  if pd.isna(city):\n      return \'unknown\'\n  city = str(city).lower().strip()\n  city=re.sub(r\'[^a-z\\s]\',\' \',city)\n  city=re.sub(r\'\\s+\'," ",city).strip()\n  city=city.title()\n  if len(city)<2 :\n    return \'unknown\'\namazon[\'City\']=amazon[\'City\'].apply(clean)  '

In [120]:
amazon.groupby('City')['Amount'].sum()

City
Aalo                      1099.0
Aamby Valley              3156.0
Abhayapuri                1034.0
Abhayapuri Bongaigaon      487.0
Abohar                    3739.0
                           ...
Zirakpur Mohali            771.0
Zirakpur Punjab            416.0
Zirakpur Punjab Mohali    1547.0
Zuari Nagar                399.0
Zundal                    1632.2
Name: Amount, Length: 6911, dtype: float64

In [121]:
amazon['City'].sample(50)

47783               Rourkela
23772                 Puttur
68510              Ghaziabad
114515             Hyderabad
29834              Hyderabad
50701               Durgapur
120249                Mandvi
127673             New Delhi
14278                Chennai
51364              Ahmedabad
127641             Ahmedabad
64679                 Mumbai
107300            Aurangabad
58452              Bengaluru
43749             Chhindwara
118433             Rishikesh
111329               Kolkata
84302                 Palani
91848                Chennai
108012                 Jammu
11818                 Mumbai
90876               Abu Road
110949          Nagapattinam
83369                Chennai
78446              New Delhi
92654               Dehradun
23754                 Manmad
85632              Hyderabad
107682          Sarita Vihar
126682             Hyderabad
104796             Ahmedabad
45946                 Mumbai
81229                   Pune
109460             Hyderabad
69414     Thiruvananthapuram
110343         Greater Noida
46361              Allahabad
96969                Naihati
70793            Gandhinagar
5176             Vasai Virar
96317              Alappuzha
20797              Faridabad
33330              Mangaluru
128529                  Pune
113991                Almora
51845              Ghaziabad
97590                 Neduva
108441                 Noida
118931             Bengaluru
84813             Puducherry
Name: City, dtype: object

In [122]:
city_map = {
    'bengalore': 'bengaluru',
    'banglore': 'bengaluru',
    'bangalore': 'bengaluru',
    'gurgaon': 'gurugram',
    'new delhi': 'delhi',
    'bombay': 'mumbai',
    'लखनऊ': 'lucknow',

    # navi mumbai ko mat daalna, wo alag city hai
}

amazon['City'] = amazon['City'].replace(city_map)

In [123]:
amazon["City"]=amazon["City"].replace(city_map)

In [124]:
for col in ["Fulfilment",'Fulfilled_By',"Currency","Asin"]:
    print(f"Unique values for {col}:")
    print(amazon[col].unique())
    print("\n")

Unique values for Fulfilment:
['Merchant' 'Amazon']


Unique values for Fulfilled_By:
['Easy Ship' nan]


Unique values for Currency:
['INR' nan]


Unique values for Asin:
['B09KXVBD7Z' 'B09K3WFS32' 'B07WV4JV4D' ... 'B081X6MVKK' 'B0943HSR64'
 'B07N81TFNY']

# we have only one( country, currency) thats why we dont need this column

In [125]:
amazon.drop(columns=["Ship_Country","Currency"], axis= "1",inplace=True)

In [126]:
amazon.columns

Index(['Order_Id', 'Date', 'Status', 'Fulfilment', 'Sales_Channel',
       'Ship_Service_Level', 'Style', 'Sku', 'Category', 'Size', 'Asin',
       'Courier_Status', 'Qty', 'Amount', 'City', 'State', 'Postal_Code',
       'Promotion_Ids', 'B2B', 'Fulfilled_By', 'Design_No.', 'Stock',
       'Category', 'Size', 'Color', 'Day'],
      dtype='object')

In [127]:
consolidated_status_map = {
    "Shipped - Delivered to Buyer": "Delivered",
    "Shipped - Rejected by Buyer": "Return",
    "Shipped - Lost in Transit": "Lost",
    "Shipped - Out for Delivery": "Shipped",
    "Shipped - Picked Up": "Shipped",
    "Shipped - Damaged": "Return",
    "Shipping": "Shipped",
    "Shipped - Returned to Seller": "Return",
    "Pending - Waiting for Pick Up": "Pending",
    "Shipped - Lost in Transi": "Pending", # Note: 'Transi' is a typo from original data, mapping it to 'Pending'
    "Shipped - Returning to Seller": "Return_Pending"
}

amazon["Status"] = amazon["Status"].replace(consolidated_status_map)
amazon["Status"].unique()

array(['Cancelled', 'Delivered', 'Shipped', 'Return', 'Lost',
       'Return_Pending', 'Pending'], dtype=object)

In [128]:
amazon.groupby("Status")["Amount"].sum()

Status
Cancelled          6919284.3
Delivered         18650815.0
Lost                  1997.0
Pending             622409.0
Return             1278075.0
Return_Pending      107620.0
Shipped           51012478.0
Name: Amount, dtype: float64

In [129]:
amazon["Status"]=amazon["Status"].replace({"Shipped":"Delivered","Pending":"Pending_Delivery","Return_Pending":"Pending_To_Return"})
amazon["Status"].unique()

array(['Cancelled', 'Delivered', 'Return', 'Lost', 'Pending_To_Return',
       'Pending_Delivery'], dtype=object)

In [130]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 26 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales_Channel       128975 non-null  object
 5   Ship_Service_Level  128975 non-null  object
 6   Style               128975 non-null  object
 7   Sku                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  Asin                128975 non-null  object
 11  Courier_Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  Amount              121180 non-null  float64
 14  City                128975 non-null  object
 15  State               128942 non-null  object
 16  Postal_Code         128942 non-null  float64
 17  Promotion_Ids       79822 non-null   object
 18  B2B                 128975 non-null  bool
 19  Fulfilled_By        39277 non-null   object
 20  Design_No.          121269 non-null  object
 21  Stock               121269 non-null  float64
 22  Category            121269 non-null  object
 23  Size                121269 non-null  object
 24  Color               121269 non-null  object
 25  Day                 128975 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(20)
memory usage: 24.7+ MB

# i drop (promotionid) becouse its long string i check and find we can not perform any analysis on this column

category and size have two column that why rename both column and drop both column

In [131]:
cols=list(amazon.columns)
cols[22]="ddd"
cols[23]="aaa"
amazon.columns=cols
amazon.drop(columns=['ddd',"aaa","Promotion_Ids","Fulfilled_By"],inplace=True)
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales_Channel       128975 non-null  object
 5   Ship_Service_Level  128975 non-null  object
 6   Style               128975 non-null  object
 7   Sku                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  Asin                128975 non-null  object
 11  Courier_Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  Amount              121180 non-null  float64
 14  City                128975 non-null  object
 15  State               128942 non-null  object
 16  Postal_Code         128942 non-null  float64
 17  B2B                 128975 non-null  bool
 18  Design_No.          121269 non-null  object
 19  Stock               121269 non-null  float64
 20  Color               121269 non-null  object
 21  Day                 128975 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(16)
memory usage: 20.8+ MB

In [132]:
a=amazon["Amount"].isna()

In [133]:
amazon[a][["Amount","Status"]]

        Amount     Status
8          NaN  Cancelled
29         NaN  Cancelled
65         NaN  Cancelled
84         NaN  Cancelled
95         NaN  Cancelled
...        ...        ...
128903     NaN  Cancelled
128907     NaN  Cancelled
128908     NaN  Cancelled
128958     NaN  Cancelled
128967     NaN  Cancelled

[7795 rows x 2 columns]

# In Amount column have nana value becouse of cancelled order i make new amount fill column to fill 0 but we make average , meadianon original column

In [134]:
amazon["Amount_Fill"]=amazon['Amount'].fillna(0)
amazon.columns

Index(['Order_Id', 'Date', 'Status', 'Fulfilment', 'Sales_Channel',
       'Ship_Service_Level', 'Style', 'Sku', 'Category', 'Size', 'Asin',
       'Courier_Status', 'Qty', 'Amount', 'City', 'State', 'Postal_Code',
       'B2B', 'Design_No.', 'Stock', 'Color', 'Day', 'Amount_Fill'],
      dtype='object')

In [135]:
amazon[["Amount","Amount_Fill"]].head(3)

   Amount  Amount_Fill
0  647.62       647.62
1  406.00       406.00
2  329.00       329.00

In [136]:
a=amazon["Courier_Status"].isna()
amazon[a][["Status",'Courier_Status']]

           Status Courier_Status
0       Cancelled            NaN
3       Cancelled            NaN
23      Cancelled            NaN
29      Cancelled            NaN
83      Cancelled            NaN
...           ...            ...
128762  Cancelled            NaN
128808  Cancelled            NaN
128855  Cancelled            NaN
128875  Cancelled            NaN
128890  Cancelled            NaN

[6872 rows x 2 columns]

# amazon couries status me nan value ki jagah cancelled fill karenge ki sare nan ki jagah statuswale column  me cancelled hain usse match karna ke baad cancelled fill kar rahe hain

In [137]:
amazon["Courier_Status"].fillna("Cancelled",inplace=True)

/tmp/ipykernel_2515/3525120020.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  amazon["Courier_Status"].fillna("Cancelled",inplace=True)

In [138]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales_Channel       128975 non-null  object
 5   Ship_Service_Level  128975 non-null  object
 6   Style               128975 non-null  object
 7   Sku                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  Asin                128975 non-null  object
 11  Courier_Status      128975 non-null  object
 12  Qty                 128975 non-null  int64
 13  Amount              121180 non-null  float64
 14  City                128975 non-null  object
 15  State               128942 non-null  object
 16  Postal_Code         128942 non-null  float64
 17  B2B                 128975 non-null  bool
 18  Design_No.          121269 non-null  object
 19  Stock               121269 non-null  float64
 20  Color               121269 non-null  object
 21  Day                 128975 non-null  object
 22  Amount_Fill         128975 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(1), object(16)
memory usage: 21.8+ MB

In [139]:
a=amazon["State"].isna()
amazon[a][['State',"City"]]

       State     City
1871     NaN  Unknown
1872     NaN  Unknown
8752     NaN  Unknown
11215    NaN  Unknown
13252    NaN  Unknown
15688    NaN  Unknown
16787    NaN  Unknown
18351    NaN  Unknown
22930    NaN  Unknown
24986    NaN  Unknown
30379    NaN  Unknown
37963    NaN  Unknown
37964    NaN  Unknown
60986    NaN  Unknown
63040    NaN  Unknown
73675    NaN  Unknown
73746    NaN  Unknown
73771    NaN  Unknown
73772    NaN  Unknown
73911    NaN  Unknown
80011    NaN  Unknown
80092    NaN  Unknown
80455    NaN  Unknown
84008    NaN  Unknown
84757    NaN  Unknown
104201   NaN  Unknown
106498   NaN  Unknown
124215   NaN  Unknown
124357   NaN  Unknown
124358   NaN  Unknown
124359   NaN  Unknown
125385   NaN  Unknown
126620   NaN  Unknown

In [140]:
import re
import pandas as pd

def clean(text):
    if pd.isna(text):
        return 'Unknown'

    text = str(text).lower().strip()
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    if len(text) < 2:
        return 'Unknown'

    return text.title()

In [141]:
amazon["State"]=amazon["State"].apply(clean)

In [142]:
amazon.dropna(subset= ["City","State"],how="all")
state_map=amazon[["City","State"]].drop_duplicates(subset="City").set_index("City")["State"]
amazon["State"].fillna(amazon["City"].map(state_map))

0          Maharashtra
1            Karnataka
2          Maharashtra
3           Puducherry
4           Tamil Nadu
              ...
128970       Telangana
128971         Haryana
128972       Telangana
128973         Gujarat
128974    Chhattisgarh
Name: State, Length: 128975, dtype: object

In [143]:
amazon["City"]=amazon["City"].apply(clean)

In [144]:
amazon[a][["City","State"]]

           City    State
1871    Unknown  Unknown
1872    Unknown  Unknown
8752    Unknown  Unknown
11215   Unknown  Unknown
13252   Unknown  Unknown
15688   Unknown  Unknown
16787   Unknown  Unknown
18351   Unknown  Unknown
22930   Unknown  Unknown
24986   Unknown  Unknown
30379   Unknown  Unknown
37963   Unknown  Unknown
37964   Unknown  Unknown
60986   Unknown  Unknown
63040   Unknown  Unknown
73675   Unknown  Unknown
73746   Unknown  Unknown
73771   Unknown  Unknown
73772   Unknown  Unknown
73911   Unknown  Unknown
80011   Unknown  Unknown
80092   Unknown  Unknown
80455   Unknown  Unknown
84008   Unknown  Unknown
84757   Unknown  Unknown
104201  Unknown  Unknown
106498  Unknown  Unknown
124215  Unknown  Unknown
124357  Unknown  Unknown
124358  Unknown  Unknown
124359  Unknown  Unknown
125385  Unknown  Unknown
126620  Unknown  Unknown

In [145]:
# Drop rows where 'City' or 'State' is 'Unknown'
initial_rows = amazon.shape[0]
amazon= amazon[~((amazon['City'] == 'Unknown') | (amazon['State'] == 'Unknown'))]

print(f"Initial number of rows: {initial_rows}")

Initial number of rows: 128975

Now, let's verify that 'Unknown' is no longer present in the unique values for 'City' and 'State'.

In [146]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128938 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128938 non-null  object
 1   Date                128938 non-null  datetime64[ns]
 2   Status              128938 non-null  object
 3   Fulfilment          128938 non-null  object
 4   Sales_Channel       128938 non-null  object
 5   Ship_Service_Level  128938 non-null  object
 6   Style               128938 non-null  object
 7   Sku                 128938 non-null  object
 8   Category            128938 non-null  object
 9   Size                128938 non-null  object
 10  Asin                128938 non-null  object
 11  Courier_Status      128938 non-null  object
 12  Qty                 128938 non-null  int64
 13  Amount              121145 non-null  float64
 14  City                128938 non-null  object
 15  State               128938 non-null  object
 16  Postal_Code         128938 non-null  float64
 17  B2B                 128938 non-null  bool
 18  Design_No.          121233 non-null  object
 19  Stock               121233 non-null  float64
 20  Color               121233 non-null  object
 21  Day                 128938 non-null  object
 22  Amount_Fill         128938 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(1), object(16)
memory usage: 22.7+ MB

B2B boolean data type tha isse maine yes No me change kiya for better understanding and dashboarding

In [147]:
amazon['B2B'] = amazon['B2B'].astype(str).str.strip().str.title()
amazon['B2B']=amazon['B2B'].replace({"True":"Yes","False":"No"})
amazon['B2B'].unique()

array(['No', 'Yes'], dtype=object)

har style ka ek hi color hota hain to hum khali color ko isse hi map kar ke bharenge

In [148]:
style_color=amazon.dropna(subset=["Style"]).drop_duplicates("Style").set_index("Style")["Color"]
style_color
amazon["Color"]=amazon["Color"].fillna(amazon["Style"].map(style_color))
amazon["Color"]=amazon["Color"].apply(clean)

In [149]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128938 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128938 non-null  object
 1   Date                128938 non-null  datetime64[ns]
 2   Status              128938 non-null  object
 3   Fulfilment          128938 non-null  object
 4   Sales_Channel       128938 non-null  object
 5   Ship_Service_Level  128938 non-null  object
 6   Style               128938 non-null  object
 7   Sku                 128938 non-null  object
 8   Category            128938 non-null  object
 9   Size                128938 non-null  object
 10  Asin                128938 non-null  object
 11  Courier_Status      128938 non-null  object
 12  Qty                 128938 non-null  int64
 13  Amount              121145 non-null  float64
 14  City                128938 non-null  object
 15  State               128938 non-null  object
 16  Postal_Code         128938 non-null  float64
 17  B2B                 128938 non-null  object
 18  Design_No.          121233 non-null  object
 19  Stock               121233 non-null  float64
 20  Color               128938 non-null  object
 21  Day                 128938 non-null  object
 22  Amount_Fill         128938 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(17)
memory usage: 23.6+ MB

In [150]:
amazon[["Design_No.","Style"]]

       Design_No.    Style
0          SET389   SET389
1         JNE3781  JNE3781
2         JNE3371  JNE3371
3           J0341    J0341
4         JNE3671  JNE3671
...           ...      ...
128970    JNE3697  JNE3697
128971     SET401   SET401
128972      J0157    J0157
128973      J0012    J0012
128974      J0003    J0003

[128938 rows x 2 columns]

Design_No and style are same thats why i drop design no column

In [151]:
amazon.drop(columns="Design_No.",inplace=True)

In [152]:
def clen(all):
  all.strip()
  return all

In [153]:
amazon["Amount"] = pd.to_numeric(amazon["Amount"], errors='coerce')

In [154]:
amazon["Category"]=amazon["Category"].apply(clen)
amazon["Sku"]=amazon["Sku"].apply(clen)

In [155]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128938 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128938 non-null  object
 1   Date                128938 non-null  datetime64[ns]
 2   Status              128938 non-null  object
 3   Fulfilment          128938 non-null  object
 4   Sales_Channel       128938 non-null  object
 5   Ship_Service_Level  128938 non-null  object
 6   Style               128938 non-null  object
 7   Sku                 128938 non-null  object
 8   Category            128938 non-null  object
 9   Size                128938 non-null  object
 10  Asin                128938 non-null  object
 11  Courier_Status      128938 non-null  object
 12  Qty                 128938 non-null  int64
 13  Amount              121145 non-null  float64
 14  City                128938 non-null  object
 15  State               128938 non-null  object
 16  Postal_Code         128938 non-null  float64
 17  B2B                 128938 non-null  object
 18  Stock               121233 non-null  float64
 19  Color               128938 non-null  object
 20  Day                 128938 non-null  object
 21  Amount_Fill         128938 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(16)
memory usage: 22.6+ MB

In [156]:
amazon["Sales_Channel"].unique()
amazon["Sales_Channel"].replace({"Amazon.in": "Amazon"}, inplace=True)
amazon["Ship_Service_Level"]=amazon["Ship_Service_Level"].str.strip().str.title()

/tmp/ipykernel_2515/2385675879.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  amazon["Sales_Channel"].replace({"Amazon.in": "Amazon"}, inplace=True)

In [157]:
amazon["Ship_Service_Level"].unique()

array(['Standard', 'Expedited'], dtype=object)

In [164]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128938 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_Id            128938 non-null  object
 1   Date                128938 non-null  datetime64[ns]
 2   Status              128938 non-null  object
 3   Fulfilment          128938 non-null  object
 4   Sales_Channel       128938 non-null  object
 5   Ship_Service_Level  128938 non-null  object
 6   Style               128938 non-null  object
 7   Sku                 128938 non-null  object
 8   Category            128938 non-null  object
 9   Size                128938 non-null  object
 10  Asin                128938 non-null  object
 11  Courier_Status      128938 non-null  object
 12  Qty                 128938 non-null  int64
 13  Amount              121145 non-null  float64
 14  City                128938 non-null  object
 15  State               128938 non-null  object
 16  Postal_Code         128938 non-null  float64
 17  B2B                 128938 non-null  object
 18  Stock               121233 non-null  float64
 19  Color               128938 non-null  object
 20  Day                 128938 non-null  object
 21  Amount_Fill         128938 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(16)
memory usage: 22.6+ MB

In [165]:
amazon[["Order_Id","Sku"]].drop_duplicates().inplace=True

Once downloaded, you can load it into a pandas DataFrame like this:

In [ ]:
# Assuming the downloaded file is a CSV
# df = pd.read_csv(file_path)
# display(df.head())

In [168]:
from google.colab import files

amazon.to_csv('amazon_sales_clean.csv', index=False)

# 3. Download karo
files.download('amazon_sales_clean.csv')

In [ ]:
amazon["Sku"]